version: '{build}'

platform: Any CPU

clone_folder: c:\go\src\github.com\libeclipse\dissident

environment:
  GOPATH: c:\go

install:
- set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
- go version

build_script:
- go build -race -v .

test_script:
    - go test -race -v ./coffer/...
    - go test -race -v ./crypto/...
    - go test -race -v ./data/...
    - go test -race -v ./stdin/...
    - go test -race -v ./

notifications:
- provider: Slack
  incoming_webhook:
    secure: 9hDxjNAP1MM9K5R70lukmCLr3IZfRWawlHWyGTNEvE9K8hKsmvtPl2uxBeq7FT6mo+tFNqTHgJyNZDSjBVOHlt4oUs7qrWxH7jqJKTX+HoQ=
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
